name: Validate Vocabulary

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: gh-pages
        clean: false
        fetch-depth: 0
    - name: Copy vocabulary
      run: git restore --source origin/master oc-acl.ttl
    - name: Rename vocabulary
      run: mv -f oc-acl.ttl oc-acl
    - name: Commit changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add -A
        git commit -m "update vocabulary in gh-pages"
        git push
