name: Validate Vocabulary

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        clean: false
    - uses: actions/checkout@v3
      with:
        ref: gh-pages
        clean: false
    - name: Copy vocabulary
      run: git restore --source master oc-acl.ttl
    - name: Rename vocabulary
      run: mv oc-acl.ttl
    - name: Commit changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.comgit add -A
        git commit -m "update vocabulary in gh-pages"
        git push
